name: Code Statistics
run-name: Creating code statistics on ${{ github.repository }}
on: 
  push:
    branches:
      - master  # Trigger the workflow only on pushes to the master branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  Lines-of-code:
    runs-on: ubuntu-latest
    container: 
      image: aldanial/cloc:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # Ensure the master branch is checked out
      - name: Install cloc
        run: apt-get update && apt-get install -y cloc
      - name: Run cloc analysis on code
        run: cloc .
