name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    #if: github.actor == 'dependabot[bot]'  # only run for Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # your project's version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python run.py
