name: Docker image scanning
on:
  workflow_dispatch:

jobs:
  Dynamic-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
          
      - name: Build the docker iamge
        run: docker build . -t suricatajs:testsec
        
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: suricatajs:testsec
          scan-type: image
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL, HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          
